version: "3"
services:
    web:
        build: app
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER_NAME: sketch_it_system
            DB_NAME: main.sql
            DB_PASSWORD: ske1ch_pass_!t_system_password
    db:
        build: db
        restart: always
        environment:
            MYSQL_USER: sketch_it_system
            MYSQL_PASSWORD: ske1ch_pass_!t_system_password